options:
  formatter: stylish
  merge-default-rules: true
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - '**/partials/scss/common/main.scss'
    - '**/partials/scss/footer/*.scss'
    - 'assets/scss/hugo-templates/*.scss'
rules:
