language: go
before_install:
  - sudo apt update
install:
  - sudo apt -y install tidy python-pygments
script: "FROM_YAML=yes ./ci/travis-cmd.sh"
dist: bionic
branches:
  only:
  - master
  - testing
  - /^stable-[0-9.]+$/
  - /^\d+\.\d+\.\d+$/
  - /^\d+\.\d+\-[a-zA-Z0-9_-]+$/
  - devel
go:
  - 1.12
