
baseURL = "https://example.com/"
description = "Modules for OldNew Mashup Theme (the new version)"

[module]
[module.hugoVersion]
min = "0.57.2"
[[module.imports]]
path="github.com/cshoredaniel/necolas-normalize.css@local-w3org-validation-clean"
[[module.imports.mounts]]
source="normalize.css"
target="assets/css/normalize.css"

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.thecshore.com"
  copyright = "© 2018-2019 Daniel F. Dickinson"
