[build]
    publish = "exampleSite/public/"
    command = "sh -c 'cd exampleSite && ln -s ../.. themes/new-oldnew-mashup && hugo --minify -b https://new-oldnew-mashup.danielfdickinson.ca/'"

[context.production.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"


[context.deploy-preview]
    command = "sh -c \"cd exampleSite && ln -s ../.. themes/new-oldnew-mashup && hugo --minify --buildFuture -b $DEPLOY_PRIME_URL\""

[context.deploy-preview.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
    command = "sh -c \"cd exampleSite && ln -s ../.. themes/new-oldnew-mashup && hugo --minify --buildFuture -b $DEPLOY_PRIME_URL\""

[context.branch-deploy.environment]
    HUGO_VERSION = "0.74.3"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"
