[build]
    publish = "exampleSite/public/"
    command = "sh -c 'cd exampleSite && hugo --verbose --gc --minify'"

[context.production.environment]
    HUGO_VERSION = "0.74.2"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"