# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Pure OldNew Mashup"
license = "MIT"
licenselink = "https://github.com/cshoredaniel/hugo-pure-oldnew-mashup/blob/master/LICENSE.md"
description = "Hugo Theme mixing old school design elements with new-era Pure CSS and others"
homepage = "https://www.thecshore.com/hugo-themes"
tags = ['hugo', 'pure', 'old-school']
features = ['blog']
min_version = "0.31.1"

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.thecshore.com"
