# Config for using theme as Hugo website

baseURL = 'https://example.com/'
languageCode = 'en-ca'
languageLang = 'en'
title = 'Oldnew Mashup'
enableGitInfo = true
theme = 'new-oldnew-mashup'
pygmentsUseClasses = true
pygmentsCodeFences = true
summaryLength = 30
description = "Sample site for OldNew Mashup Theme (the new version)"
author = "Daniel F. Dickinson <cshored@thecshore.com>"
themesDir = "../.."
min_version = "0.59.1"

[params]
  siteid = 'OldNew Mashup'
  licenses = ['CC-BY-4.0']
  copyright = '© 2018-2019 Daniel F. Dickinson'
  GitHubRepo = 'cshoredaniel/new-oldnew-mashup'
  rssfeedlink = true
  validatorlink = true
  site_badge_graphic = "/images/sample_image.png"
  site_badge_graphic_alt_text = "[Logo for Hugo OldNew Mashup Theme Homepage]"
  splash_images_bundle = "/siteentry/splash-images"
  enable_search = true
  time_types = ["Viverra Justo", "Ipsum"]
  recent_changes = "/siteentry/recent-changes"
  recent_events = "/siteentry/recent-events"
  recent_news = "/siteentry/recent-news"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[frontmatter]
  lastmod = ["lastmod",":git","date","publishDate"]
  date = ["date","publishDate",":git","lastmod"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  license = "licenses"

[module]

[module.hugoVersion]
  min = "0.59.1"

  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.imports]]
  # We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
  path="github.com/bep/empty-hugo-module"
