# Config for using theme as Hugo website

#baseURL = 'http://example.com/'
languageCode = 'en-ca'
languageLang = 'en'
title = 'Oldnew Mashup'
enableGitInfo = true
theme = 'oldnew-mashup'
pygmentsUseClasses = true
pygmentsCodeFences = true
summaryLength = 30
description = "Sample site for OldNew Mashup Theme (the new version)"
author = "Daniel F. Dickinson <cshored@thecshore.com>"

[params]
  siteid = 'OldNew Mashup'
  license = 'CC-BY-4.0'
  copyright = '© 2018 Daniel F. Dickinson'
  GitHubRepo = 'cshoredaniel/hugo-oldnew-mashup'
  pygmentsUsesClasses = true
  pygmentsCodeFences = true
  rssfeedlink = true
  validatorlink = true
  site_badge_graphic = "/images/sample_image.png"
  site_badge_graphic_alt_text = "[Logo for Hugo OldNew Mashup Theme Homepage]"
  splash_images_bundle = "siteentry/splash-images"
  enable_search = true

[outputs]
  home = ["HTML", "JSON", "RSS"]

[frontmatter]
  lastmod = ["lastmod",":git","date","publishDate"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
