# Config for using theme as Hugo website

baseURL = 'http://example.com/'
languageCode = 'en-ca'
languageLang = 'en'
title = 'Oldnew Mashup'
enableGitInfo = true
theme = 'oldnew-mashup'
pygmentsUseClasses = true
pygmentsCodeFences = true
summaryLength = 30

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  siteid = 'OldNew Mashup'
  license = 'CC-BY-4.0'
  copyright = '© 2018 Daniel F. Dickinson'
  GitHubRepo = 'cshoredaniel/hugo-oldnew-mashup'
  pygmentsUsesClasses = true
  pygmentsCodeFences = true
  rssfeedlink = true
  validatorlink = true
  site_badge_graphic = "/images/sample_image.png"
  site_badge_graphic_alt_text = "[Logo for Hugo OldNew Mashup Theme Homepage]"
  splash_images_bundle = "siteentry/splash-images"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[frontmatter]
  lastmod = ["lastmod",":git","date","publishDate"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
